source 'https://rubygems.org'

gem 'rails', '3.2.14'
gem 'pg'
gem 'jquery-rails'
gem 'haml-rails'
gem 'cancan'
gem 'bcrypt-ruby', '~> 3.0.0'
gem 'rmagick'
gem 'carrierwave'
gem 'fog', '~> 1.3.1'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

group :development do
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'better_errors'
  gem 'binding_of_caller'
end
